#!/usr/bin/env python3
import os
import sys
def main(argv):
	json_path = "/usr/share/cockpit/45drives-disks/" + argv[0]
	if os.path.exists(json_path):
		f = open(json_path,"r")
		print(f.read())
		f.close()
	else:
		print("\{\"error\": \"cannot locate {j}\"\}".format(j=json_path))
		sys.exit(1)

if __name__ == "__main__":
    main(sys.argv[1:])