#!/usr/bin/env python3
import os
import sys
def main(argv):
	json_path = "/usr/share/cockpit/45drives-motherboard/" + argv[0]
	if os.path.exists(json_path):
		f = open(json_path,"r")
		print(f.read());
		f.close()

if __name__ == "__main__":
    main(sys.argv[1:])