#!/usr/bin/env python3
import os
import json
import sys


def main():
    json_path = "/etc/45drives/server_info/server_info.json"
    if os.path.exists(json_path):
        f = open(json_path, "r")
        print(f.read())
        f.close()
    else:
        print("/etc/45drives/server_info/server_info.json not found.")
        sys.exit(1)


if __name__ == "__main__":
    main()
